server:
  port: 12000
  address: 54.196.153.112

spring:
  mvc:
    view:
      suffix: .html
  thymeleaf:
    prefix: classpath:/templates


logging:
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [%4L] - %m%n"
    file: "[%d{HH:mm:ss.SSS}][%-5level][%t][%logger.%method:line%line] - %msg%n"
  file:
    name: "${messenger.home:/tmp}/logs/messenger-server.log"