spring:
  profiles:
    active: prod

  r2dbc:
    url: r2dbc:mariadb://35.216.1.250:3306/messenger?characterEncoding=utf8&serverTimezone=UTC
    username: teamride
    password: 1234

  logging:
    level:
      org.springframework.r2dbc.core: debug